version: '3.9'

services:
  db:
    image: postgres:15.12-alpine3.21
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
  
  backend:
    build: ./backend
    restart: always
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/mydb
    ports:
      - "2222:2222"
  
  frontend:
    build: ./frontend
    restart: always
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:2222
    ports:
      - "3000:3000"

volumes:
  postgres-data: