services:
  db:
    image: postgres:15.12-alpine3.21
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: scheduler_courses_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
  
  backend:
    build: ./backend
    restart: always
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/scheduler_courses_db
      - PORT=2222
      - JWT_SECREET=iR++LRtav0AYML1GMXz+/XDk85uEnnOVk7QVSJF7TMw
      - CLIENT_URL=http://192.168.221.41:5000
      - NODE_ENV=development
      - TZ='Asia/Jakarta'
    ports:
      - "4000:2222"
  
  frontend:
    build: ./frontend
    restart: always
    depends_on:
      - backend
    environment:
      - JWT_SECREET=iR++LRtav0AYML1GMXz+/XDk85uEnnOVk7QVSJF7TMw
      - NEXT_PUBLIC_NODE_ENV=development
      - TZ='Asia/Jakarta'
    ports:
      - "5000:3000"

volumes:
  postgres-data: